### PR TITLE
Build sauerbraten server from source & use alpine for smaller images

### PR DESCRIPTION
**Pull request by jreitz-dev**
- use Alpine instead of Ubuntu
- download latest source repo instead of zipped specific version
- update `run.sh` to accommodate changes
  - use `-e` to check if linked file exists instead of regular file (`-f`)

### CODE REVIEW

**Comment by captainGeech42** [comment]
Is the latest server code from source backwards compatible with clients that aren't running the latest commit?

**Comment by jreitz-dev** [comment]
As of V2.60 this is not the case.

Some of my friends tried installing Sauerbraten from the PPA and the version there is outdated (2.59) - this leads to an issue since my Sauerbraten Version is 2.60.
So no - they are not always backwards compatible.

Tags would solve this.

**Comment by jreitz-dev** [comment]
Are you planning to merge this or should I close this?

**Comment by captainGeech42** [comment]
Hi, sorry @jkonze , thank you for the ping, merging now. Thanks for your contribution!

**Pull request merged**
